version: '3'

services:
  backend:
    build:
      context: ./server
      dockerfile: DockerFile
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb+srv://amenkorchane:amenkorchanemongodb@cluster0.nvupipm.mongodb.net/?retryWrites=true&w=majority
      - JWT_SECRET=mohsenyejour
      # Add other environment variables as needed

  frontend:
    build:
      context: ./client
      dockerfile: DockerFile
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo-data:
