version: '3.3'

services:
  frontend:
    container_name: ng_frontend
    build: ./client
    ports:
      - 3000:3000
    working_dir: /client
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:3001
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      timeout: 10s
      retries: 5

  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
  backend:
    container_name: ng_backend
    build: ./server
    ports:
      - 3001:3001
    working_dir: /server
    depends_on:
      - mongo
    environment:
      - JWT_SECRET=mohsenyejour
      - MONGO_URL=mongodb+srv://amenkorchane:amenkorchanemongodb@cluster0.nvupipm.mongodb.net/?retryWrites=true&w=majority