version: '3'

services:
  backend:
    build:
      context: server
      dockerfile: DockerFile.server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://amenkorchane:amenkorchanemongodb@cluster0.nvupipm.mongodb.net/?retryWrites=true&w=majority
      # Add other environment variables as needed

  frontend:
    build:
      context: client
      dockerfile: DockerFile.client
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo-data:
