version: '3.5'

services:
  frontend:
    container_name: ng_frontend
    build: ./client
    ports:
      - 3000:3000
    working_dir: /client
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001

  backend:
    container_name: ng_backend
    build: ./server
    ports:
      - 3001:3001
    working_dir: /server
    depends_on:
      db:
        condition: service_healthy
    environment:
      - APP_PORT=3001
      - JWT_SECRET=mohsenyejour
      - MONGO_URI=mongodb+srv://amenkorchane:amenkorchanemongodb@cluster0.nvupipm.mongodb.net/?retryWrites=true&w=majority

   